name: festeasy
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  carousel_slider: ^5.0.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.2
  font_awesome_flutter: ^10.12.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_fonts: ^8.0.0
  http: ^1.2.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  retrofit: ^4.9.2
  supabase_flutter: ^2.12.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.4
  very_good_analysis: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/app_icon.jpeg
    - assets/icons/logo.jpeg

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.jpeg"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon.jpeg"
  remove_alpha_ios: true
